#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
SECONDS=0
LOCKFILE="/tmp/$(basename $0)_$(whoami)"
LOCKFD="150"
fecha=$(date +%d-%m-%Y)
borrar=$(date -d"30 days ago" +%Y-%m-%d)
aws_access_key_id="XXXXXXXXXXXXXXXXXXX"
aws_secret_access_key="XXXXXXXXXXXXXX"
correo='swaks -4 --to destiny@mail.com --from origin@mail.com --server origin@mail.com:587 -tls --auth LOGIN --auth-user origin@mail.com --auth-password XXXXXXXXXXX'

function clean_1() {
	rm -f /tmp/$(basename $0)_$(whoami)
}

function lock() {
	echo {LOCKFD}>$LOCKFILE
	flock -n $LOCKFD
}

function exit_error() {
	echo "ERROR: Ya hay una instancia en ejecución. Saliendo"
	exit 1
}

if [[ "$EUID" = "0" ]]; then
	echo -e "\e[00;31mERROR: NO debe ser root.\e[00m"
	exit 1
fi

trap "clean_1; exit" 0 1 2 3 9 15
lock || exit_error
clear

ids=$(aws ec2 describe-snapshots --output text --owner-ids 012345678912 --query "Snapshots[?(StartTime<='$borrar')].[SnapshotId]")
listaec2=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --output text)

echo "Creando snapshots EC2"
for i in ${listaec2[@]}; do
	nombre=$(aws ec2 describe-instances --instance-id $i --query 'Reservations[].Instances[].[Tags[?Key==`Name`]| [0].Value]' --output text)
	volume=$(aws ec2 describe-instances --instance-id $i --query 'Reservations[].Instances[][].BlockDeviceMappings[].Ebs[].VolumeId' --output text)
	echo "instancia $i"
	echo "nombre $nombre"
	for j in ${volume[@]}; do
		echo "volumen $j"
		aws ec2 create-snapshot --region us-west-1 --volume-id $j --description "$i - $nombre"
		echo "###############################"
	done
done

echo "Limpiando snapshots EC2 viejos"
for i in ${ids[@]}; do
	echo "eliminando $i"
        aws ec2 delete-snapshot --snapshot-id $i
done
echo "########################################"

echo "Limpiando snapshots LightSail"
snapshotsToKeep=4
numberOfSnapshots=$(aws lightsail --region us-east-1 get-instance-snapshots | jq '.[]|length')
SnapshotNames=$(aws lightsail --region us-east-1 get-instance-snapshots | jq '.[] | sort_by(.createdAt) | .[].name')
while IFS= read -r line
do
let "i++"

if (($i <= $numberOfSnapshots-$snapshotsToKeep)); then
	snapshotToDelete=$(echo "$line" | tr -d '"')
	aws lightsail --region us-east-1 delete-instance-snapshot --instance-snapshot-name $snapshotToDelete
	echo "Deleted Snapshot: " + $line
fi
done <<< "$SnapshotNames"
echo "########################################"

echo "Creando snapshots LightSail"
echo "EXAMPLE"
aws lightsail create-instance-snapshot --region us-east-1 --instance-name EXAMPLE --instance-snapshot-name EXAMPLE-$fecha
echo "########################################"

$correo --header "Subject: Se ejecutaron los snapshot de las instancias en AWS %DATE%" --body "Se realizaron los snapshot de las instancias en AWS"
echo "duracion $SECONDS segundos"
echo -e "\e[00;1;92mFinalizado.\e[00m"
exit 0
